version: '3.9'
services:
  postgres:
    image: postgres:15
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tf}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres-volume:
